development:
  database: madmodel
  adapter:  pdo_mysql
  host:     localhost
  username: root
  password:

test:
  database: madmodel_test
  adapter:  pdo_mysql
  host:     localhost
  username: root
  password:

production:
  database: madmodel
  adapter:  pdo_mysql
  host:     localhost
  username: root
  password:
